//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBook_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Book
    {
   
        public int id { get; set; }

        [DisplayName("Book Name")]
        [Required(ErrorMessage = "Name is Required")]
        public string Name { get; set; }


        [DisplayName("Book Image")]
        public string Image_path { get; set; }


        [DisplayName("Book Category")]
        [Required(ErrorMessage = "Category is Required")]
        public string Category { get; set; }

        [DisplayName("Pdf path")]
        public string Pdf_path { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }

        public HttpPostedFileBase PdfFile { get; set; }

        public byte[] FileContent { get; set; }

        public string Pdf_Filename { get; set; }

    }
}
